homepage:
    path: /
    controller: App\Controller\HomeController::index

category:
    path: /category/{id}
    controller: App\Controller\CategoryController::index

post:
    path: /post/{id}
    controller: App\Controller\PostController::show
